name: Trigger auto deployment for spring-boot-example

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/spring-boot-example-AutoDeployTrigger-79ffb9e3-81f6-4ad1-941c-49f0ae3723ac.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: daren.azurecr.io
          username: ${{ secrets.SPRINGBOOTEXAMPLE_REGISTRY_USERNAME }}
          password: ${{ secrets.SPRINGBOOTEXAMPLE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: daren.azurecr.io/spring-boot-example:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPRINGBOOTEXAMPLE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n spring-boot-example -g explore-container --server daren.azurecr.io --username  ${{ secrets.SPRINGBOOTEXAMPLE_REGISTRY_USERNAME }} --password ${{ secrets.SPRINGBOOTEXAMPLE_REGISTRY_PASSWORD }}
            az containerapp update -n spring-boot-example -g explore-container --image daren.azurecr.io/spring-boot-example:${{ github.sha }}
